from tkinter import *
from backend import *
window=Tk()
window.title('mordern periodic table')
window.config(bg='white')
b1=Button(window,text='H',bg='light green',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:H())
b1.grid(row=1,column=0,padx=2,pady=2)
b2=Button(window,text='Li',bg='red',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Li())
b2.grid(row=2,column=0,padx=2,pady=2)
b3=Button(window,text='Na',bg='red',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Na())
b3.grid(row=3,column=0,padx=2,pady=2)
b4=Button(window,text='K',bg='red',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:K())
b4.grid(row=4,column=0,padx=2,pady=2)
b5=Button(window,text='Rb',bg='red',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Rb())
b5.grid(row=5,column=0,padx=2,pady=2)
b6=Button(window,text='Cs',bg='red',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Cs())
b6.grid(row=6,column=0,padx=2,pady=2)
b7=Button(window,text='Fr',bg='red',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Fr())
b7.grid(row=7,column=0,padx=2,pady=2)


b8=Button(window,text='Be',bg='orange',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Be())
b8.grid(row=2,column=1,padx=2,pady=2)
b9=Button(window,text='Mg',bg='orange',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Mg())
b9.grid(row=3,column=1,padx=2,pady=2)
b10=Button(window,text='Ca',bg='orange',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ca())
b10.grid(row=4,column=1,padx=2,pady=2)
b11=Button(window,text='Sr',bg='orange',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Sr())
b11.grid(row=5,column=1,padx=2,pady=2)
b12=Button(window,text='Ba',bg='orange',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ba())
b12.grid(row=6,column=1,padx=2,pady=2)
b13=Button(window,text='Ra',bg='orange',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ra())
b13.grid(row=7,column=1,padx=2,pady=2)


b8=Button(window,text='Sc',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Sc())
b8.grid(row=4,column=2,padx=2,pady=2)
b9=Button(window,text='Y',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Y())
b9.grid(row=5,column=2,padx=2,pady=2)
b10=Button(window,text='lanthanoid',bg='sky blue',fg='black',bd=3,font=('Times',10),width=6,height=2)
b10.grid(row=6,column=2,padx=2,pady=2)
b11=Button(window,text='actinoids',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2)
b11.grid(row=7,column=2,padx=2,pady=2)


b8=Button(window,text='Ti',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ti())
b8.grid(row=4,column=3,padx=2,pady=2)
b9=Button(window,text='Zr',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Zr())
b9.grid(row=5,column=3,padx=2,pady=2)
b10=Button(window,text='Hf',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Hf())
b10.grid(row=6,column=3,padx=2,pady=2)
b11=Button(window,text='Rf',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Rf())
b11.grid(row=7,column=3,padx=2,pady=2)


b8=Button(window,text='V',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:V())
b8.grid(row=4,column=4,padx=2,pady=2)
b9=Button(window,text='Nb',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Nb())
b9.grid(row=5,column=4,padx=2,pady=2)
b10=Button(window,text='Ta',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ta())
b10.grid(row=6,column=4,padx=2,pady=2)
b11=Button(window,text='Db',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Db())
b11.grid(row=7,column=4,padx=2,pady=2)


b8=Button(window,text='Cr',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Cr())
b8.grid(row=4,column=5,padx=2,pady=2)
b9=Button(window,text='Mo',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Mo())
b9.grid(row=5,column=5,padx=2,pady=2)
b10=Button(window,text='W',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:W())
b10.grid(row=6,column=5,padx=2,pady=2)
b11=Button(window,text='Sg',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Sg())
b11.grid(row=7,column=5,padx=2,pady=2)


b8=Button(window,text='Mn',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Mn())
b8.grid(row=4,column=6,padx=2,pady=2)
b9=Button(window,text='Tc',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Tc())
b9.grid(row=5,column=6,padx=2,pady=2)
b10=Button(window,text='Re',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Re())
b10.grid(row=6,column=6,padx=2,pady=2)
b11=Button(window,text='Bh',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Bh())
b11.grid(row=7,column=6,padx=2,pady=2)

b8=Button(window,text='Fe',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Fe())
b8.grid(row=4,column=7,padx=2,pady=2)
b9=Button(window,text='Ru',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ru())
b9.grid(row=5,column=7,padx=2,pady=2)
b10=Button(window,text='Os',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Os())
b10.grid(row=6,column=7,padx=2,pady=2)
b11=Button(window,text='Hs',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Hs())
b11.grid(row=7,column=7,padx=2,pady=2)


b8=Button(window,text='Co',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Co())
b8.grid(row=4,column=8,padx=2,pady=2)
b9=Button(window,text='Rh',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Rh())
b9.grid(row=5,column=8,padx=2,pady=2)
b10=Button(window,text='Ir',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ir())
b10.grid(row=6,column=8,padx=2,pady=2)
b11=Button(window,text='Mt',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Mt())
b11.grid(row=7,column=8,padx=2,pady=2)

b8=Button(window,text='Ni',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ni())
b8.grid(row=4,column=9,padx=2,pady=2)
b9=Button(window,text='Pd',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Pd())
b9.grid(row=5,column=9,padx=2,pady=2)
b10=Button(window,text='Pt',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Pt())
b10.grid(row=6,column=9,padx=2,pady=2)
b11=Button(window,text='Ds',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ds())
b11.grid(row=7,column=9,padx=2,pady=2)

b8=Button(window,text='Cu',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Cu())
b8.grid(row=4,column=10,padx=2,pady=2)
b9=Button(window,text='Ag',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ag())
b9.grid(row=5,column=10,padx=2,pady=2)
b10=Button(window,text='Au',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Au())
b10.grid(row=6,column=10,padx=2,pady=2)
b11=Button(window,text='Rg',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Rg())
b11.grid(row=7,column=10,padx=2,pady=2)

b8=Button(window,text='Zn',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Zn())
b8.grid(row=4,column=11,padx=2,pady=2)
b9=Button(window,text='Cd',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Cd())
b9.grid(row=5,column=11,padx=2,pady=2)
b10=Button(window,text='Hg',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Hg())
b10.grid(row=6,column=11,padx=2,pady=2)
b11=Button(window,text='Cn',bg='yellow',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Cn())
b11.grid(row=7,column=11,padx=2,pady=2)

b8=Button(window,text='B',bg='purple',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:B())
b8.grid(row=2,column=12,padx=2,pady=2)
b9=Button(window,text='Al',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Al())
b9.grid(row=3,column=12,padx=2,pady=2)
b10=Button(window,text='Ga',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ga())
b10.grid(row=4,column=12,padx=2,pady=2)
b11=Button(window,text='In',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:In())
b11.grid(row=5,column=12,padx=2,pady=2)
b12=Button(window,text='Tl',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Tl())
b12.grid(row=6,column=12,padx=2,pady=2)
b13=Button(window,text='Nh',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Nh())
b13.grid(row=7,column=12,padx=2,pady=2)

b8=Button(window,text='C',bg='blue',fg='yellow',bd=3,font=('Times',10),width=6,height=2,command=lambda:C())
b8.grid(row=2,column=13,padx=2,pady=2)
b9=Button(window,text='Si',bg='purple',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Si())
b9.grid(row=3,column=13,padx=2,pady=2)
b10=Button(window,text='Ge',bg='purple',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ge())
b10.grid(row=4,column=13,padx=2,pady=2)
b11=Button(window,text='Sn',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Sn())
b11.grid(row=5,column=13,padx=2,pady=2)
b12=Button(window,text='Pb',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Pb())
b12.grid(row=6,column=13,padx=2,pady=2)
b13=Button(window,text='Fl',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Fl())
b13.grid(row=7,column=13,padx=2,pady=2)

b8=Button(window,text='N',bg='blue',fg='yellow',bd=3,font=('Times',10),width=6,height=2,command=lambda:N())
b8.grid(row=2,column=14,padx=2,pady=2)
b9=Button(window,text='P',bg='blue',fg='yellow',bd=3,font=('Times',10),width=6,height=2,command=lambda:P())
b9.grid(row=3,column=14,padx=2,pady=2)
b10=Button(window,text='As',bg='purple',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:As())
b10.grid(row=4,column=14,padx=2,pady=2)
b11=Button(window,text='Sb',bg='purple',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Sb())
b11.grid(row=5,column=14,padx=2,pady=2)
b12=Button(window,text='Bi',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Bi())
b12.grid(row=6,column=14,padx=2,pady=2)
b13=Button(window,text='Mc',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Mc())
b13.grid(row=7,column=14,padx=2,pady=2)

b8=Button(window,text='O',bg='blue',fg='yellow',bd=3,font=('Times',10),width=6,height=2,command=lambda:O())
b8.grid(row=2,column=15,padx=2,pady=2)
b9=Button(window,text='S',bg='blue',fg='Yellow',bd=3,font=('Times',10),width=6,height=2,command=lambda:S())
b9.grid(row=3,column=15,padx=2,pady=2)
b10=Button(window,text='Se',bg='blue',fg='Yellow',bd=3,font=('Times',10),width=6,height=2,command=lambda:Se())
b10.grid(row=4,column=15,padx=2,pady=2)
b11=Button(window,text='Te',bg='purple',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Te())
b11.grid(row=5,column=15,padx=2,pady=2)
b12=Button(window,text='Po',bg='purple',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Po())
b12.grid(row=6,column=15,padx=2,pady=2)
b13=Button(window,text='Lv',bg='dark orange',fg='dark red',bd=3,font=('Times',10),width=6,height=2,command=lambda:Lv())
b13.grid(row=7,column=15,padx=2,pady=2)

b8=Button(window,text='F',bg='pink',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:F())
b8.grid(row=2,column=16,padx=2,pady=2)
b9=Button(window,text='Cl',bg='pink',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Cl())
b9.grid(row=3,column=16,padx=2,pady=2)
b10=Button(window,text='Br',bg='pink',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Br())
b10.grid(row=4,column=16,padx=2,pady=2)
b11=Button(window,text='I',bg='pink',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:I())
b11.grid(row=5,column=16,padx=2,pady=2)
b12=Button(window,text='At',bg='pink',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:At())
b12.grid(row=6,column=16,padx=2,pady=2)
b13=Button(window,text='Ts',bg='pink',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ts())
b13.grid(row=7,column=16,padx=2,pady=2)

b1=Button(window,text='He',bg='brown',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:He())
b1.grid(row=1,column=17,padx=2,pady=2)
b2=Button(window,text='Ne',bg='brown',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ne())
b2.grid(row=2,column=17,padx=2,pady=2)
b3=Button(window,text='Ar',bg='brown',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ar())
b3.grid(row=3,column=17,padx=2,pady=2)
b4=Button(window,text='Kr',bg='brown',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Kr())
b4.grid(row=4,column=17,padx=2,pady=2)
b5=Button(window,text='Xe',bg='brown',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Xe())
b5.grid(row=5,column=17,padx=2,pady=2)
b6=Button(window,text='Rn',bg='brown',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Rn())
b6.grid(row=6,column=17,padx=2,pady=2)
b7=Button(window,text='Og',bg='brown',fg='white',bd=3,font=('Times',10),width=6,height=2,command=lambda:Og())
b7.grid(row=7,column=17,padx=2,pady=2)



b1=Button(window,text='La',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:La())
b1.grid(row=9,column=2,padx=2,pady=2)
b2=Button(window,text='Ce',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ce())
b2.grid(row=9,column=3,padx=2,pady=2)
b3=Button(window,text='Pr',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Pr())
b3.grid(row=9,column=4,padx=2,pady=2)
b4=Button(window,text='Nd',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Nd())
b4.grid(row=9,column=5,padx=2,pady=2)
b5=Button(window,text='Pm',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Pm())
b5.grid(row=9,column=6,padx=2,pady=2)
b6=Button(window,text='Sm',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Sm())
b6.grid(row=9,column=7,padx=2,pady=2)
b7=Button(window,text='Eu',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Eu())
b7.grid(row=9,column=8,padx=2,pady=2)
b8=Button(window,text='Gd',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Gd(0))
b8.grid(row=9,column=9,padx=2,pady=2)
b9=Button(window,text='Tb',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Tb())
b9.grid(row=9,column=10,padx=2,pady=2)
b10=Button(window,text='Dy',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Dy())
b10.grid(row=9,column=11,padx=2,pady=2)
b11=Button(window,text='Ho',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ho())
b11.grid(row=9,column=12,padx=2,pady=2)
b12=Button(window,text='Er',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Er())
b12.grid(row=9,column=13,padx=2,pady=2)
b13=Button(window,text='Tm',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Tm())
b13.grid(row=9,column=14,padx=2,pady=2)
b14=Button(window,text='Yb',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Yb())
b14.grid(row=9,column=15,padx=2,pady=2)
b16=Button(window,text='Lu',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Lu())
b16.grid(row=9,column=16,padx=2,pady=2)

b1=Button(window,text='Ac',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ac())
b1.grid(row=10,column=2,padx=2)
b2=Button(window,text='Th',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Th())
b2.grid(row=10,column=3,padx=2)
b3=Button(window,text='Pa',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Pa())
b3.grid(row=10,column=4,padx=2)
b4=Button(window,text='U',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:U())
b4.grid(row=10,column=5,padx=2)
b5=Button(window,text='Np',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Np())
b5.grid(row=10,column=6,padx=2)
b6=Button(window,text='Pu',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Pu())
b6.grid(row=10,column=7,padx=2)
b7=Button(window,text='Am',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Am())
b7.grid(row=10,column=8,padx=2)
b8=Button(window,text='Cm',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Cm())
b8.grid(row=10,column=9,padx=2)
b9=Button(window,text='Bk',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Bk())
b9.grid(row=10,column=10,padx=2)
b10=Button(window,text='Cf',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Cf())
b10.grid(row=10,column=11,padx=2)
b11=Button(window,text='Es',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Es())
b11.grid(row=10,column=12,padx=2)
b12=Button(window,text='Fm',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Fm())
b12.grid(row=10,column=13,padx=2)
b13=Button(window,text='Md',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Md())
b13.grid(row=10,column=14,padx=2)
b14=Button(window,text='No',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:No())
b14.grid(row=10,column=15,padx=2)
b15=Button(window,text='Lr',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Lr())
b15.grid(row=10,column=16,padx=2)

b1=Button(window,text='Ubu',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ubu())
b1.grid(row=11,column=2,padx=2,pady=2)
b2=Button(window,text='Ubb',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ubb())
b2.grid(row=11,column=3,padx=2)
b3=Button(window,text='Ubt',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ubt())
b3.grid(row=11,column=4,padx=2)
b4=Button(window,text='Ubq',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ubq())
b4.grid(row=11,column=5,padx=2)
b5=Button(window,text='Ubp',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ubp())
b5.grid(row=11,column=6,padx=2)
b6=Button(window,text='Ubh',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ubh())
b6.grid(row=11,column=7,padx=2)
b7=Button(window,text='Ubs',bg='light blue',fg='black',bd=3,font=('Times',10),width=6,height=2,command=lambda:Ubs())
b7.grid(row=11,column=8,padx=2)




b1=Button(window,text='Alkali metal',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Alkali())
b1.grid(row=1,column=18,padx=(30,2),pady=2)
b2=Button(window,text='Alkaline earth metal',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Ne())
b2.grid(row=2,column=18,padx=(30,2),pady=2)
b3=Button(window,text='Transition metal',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Ar())
b3.grid(row=3,column=18,padx=(30,2),pady=2)
b4=Button(window,text='Post transition metal',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Kr())
b4.grid(row=4,column=18,padx=(30,2),pady=2)
b5=Button(window,text='Metalloid',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Xe())
b5.grid(row=5,column=18,padx=(30,2),pady=2)
b6=Button(window,text='Halogens',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Rn())
b6.grid(row=6,column=18,padx=(30,2),pady=2)
b7=Button(window,text='Nobel gas',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Og())
b7.grid(row=7,column=18,padx=(30,2),pady=2)
b6=Button(window,text='Lanthanides',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Rn())
b6.grid(row=8,column=18,padx=(30,2),pady=2)
b7=Button(window,text='Actinides',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Og())
b7.grid(row=9,column=18,padx=(30,2),pady=2)
b6=Button(window,text='Superactinides',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Rn())
b6.grid(row=10,column=18,padx=(30,2),pady=2)
b7=Button(window,text='Other non-metal',bg='brown',fg='white',bd=3,font=('Times',10),width=30,height=2,command=lambda:Og())
b7.grid(row=11,column=18,padx=(30,2),pady=2)

        
window.mainloop()
